services:
    database:
        image: postgres
        container_name: database_queries
        restart: always
        ports: 
            - 5432:5432
        environment: 
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=queries
            - POSTGRES_DB=database_queries
        volumes: 
            - pgdata:/data/postgres
volumes: 
    pgdata:
        driver: local